### ISSUE TITLE
CamelCase or snack_case?

### ISSUE THREAD

**Issue by zinkovskiy** [OxCom/symfony3-rollbar-bundle#10]
Hi, guys. I saw, you added `rollbar_js` configuration, but under this section you used CamelCase. 
It's a bad practice use of writing compound words. 
Could you please use snake case to write configuration for `rollbar js` section as you used for `rollbar` section?

**Comment by OxCom** [comment]
Thanks for report. Current way was done to avoid extra layer of mapping configuration that should be passed to JS.
I aggree with "bad practice". Will be changed soo.

**Comment by OxCom** [comment]
Changes are in new release v2.1.0
