### ISSUE TITLE
Person tracking

### ISSUE THREAD

**Issue by sudent** [OxCom/symfony3-rollbar-bundle#14]
Hi,

For the person tracking, may I know the correct way to use it with the bundle?

I have tried defining the `person_fn` to my service, but the `getPerson()` method in my service never gets called unless I override the `person` configuration definition (https://github.com/OxCom/symfony-rollbar-bundle/blob/master/DependencyInjection/Configuration.php#L141) with the following:

`->scalarNode('person')->defaultNull()->end()` 

I try this because in rollbar-php https://github.com/rollbar/rollbar-php/blob/v1.6.3/src/DataBuilder.php#L868 it will skip the function call if `person` is not null which it isn't in default bundle config (default value is `[]`). Trying to force it to null will still result in empty array value.

I'm using PHP7.2 btw.

Thanks

**Comment by OxCom** [comment]
@sudent 
Base on a code that you pointed in a rollbar SDK:
```php
$personData = $this->person;
if (!isset($personData) && is_callable($this->personFunc)) {
        /** ... */
}
```

**Comment by OxCom** [comment]
You are right. I did mistake when adopt configuration. it should be NULL by default. please wait for fix.

**Comment by sudent** [comment]
Thanks for the quick fix! Have verified that the fix works. Thanks again 👍
