### ISSUE TITLE
Wrong parameter value in config

### ISSUE THREAD

**Issue by zinkovskiy** [OxCom/symfony3-rollbar-bundle#17]
Hello. I found some unexpected behaviour in your bundle. Could you please tell me why you placed `\Symfony\Component\Debug\Exception\FatalErrorException` to `exclude` section in config?
Simplified example.
```
$array = [];
// developer thinks that $array it is ArrayCollection
$array->first(); // For php 7 \Error will be thrown here
```
We use symfony v3.4.15
To process the error, `Symfony\Component\Debug\ErrorHandler::handleException`
will be called, which converts `Error` to `FatalThrowableError` which extends `FatalErrorException`
Look here on code: https://github.com/symfony/debug/blob/master/ErrorHandler.php#L520

As result, error will be not reported because of `exclude` default values in config.

If you want to show how to use exclude option, I suggest to create ExampleException class in SymfonyRollbarBundle which won't used anywhere and put this exception to `exclude` section.
What do you think about it?

**Comment by OxCom** [comment]
You are rignht. Just negative influence from other bundles. Exluce exceptions list will be empty by default in next release.

**Comment by OxCom** [comment]
Update has been release in v2.1.2
