### ISSUE TITLE
Add ability to collect person data

### ISSUE THREAD

**Issue by ownede** [OxCom/symfony3-rollbar-bundle#3]
Rollbar allows [Person tracking](https://rollbar.com/docs/person-tracking/). Very useful in some cases (you can track previous errors of given user etc). 

It's able to send data about logged user:
- _id_ (required)
- username (optional)
- email (optional)

As the bundle uses Monolog, [this StackOverflow answer](https://stackoverflow.com/a/33531491/841620) should help a bit. 
Of course, we should be able to configure which data we'd like to send to Rollbar.

**Comment by OxCom** [comment]
Integration done in [v2.0.7](https://github.com/OxCom/symfony3-rollbar-bundle/releases/tag/v2.0.7)
