### ISSUE TITLE
ExceptionListener tries to serialize Closure on \Error (PHP 7+)

### ISSUE THREAD

**Issue by ownede** [OxCom/symfony3-rollbar-bundle#4]
On PHP 7+ (happened on 7.1.14), the bundle tries to serialize `Closure` when it catches `\Error` based throwable (f.e `\TypeError`). 

Error:
```
Error: Uncaught Exception: Serialization of 'Closure' is not allowed in vendor/oxcom/symfony-rollbar-bundle/EventListener/ExceptionListener.php:53
```

**Comment by OxCom** [comment]
Bug fixed in [v2.0.7](https://github.com/OxCom/symfony3-rollbar-bundle/releases/tag/v2.0.7)
